### ISSUE TITLE
Just need help

### ISSUE THREAD

**Issue by ForestedDev** [KingofKFCJamal/CSGO-Case-Clicker#2]
Is there any way you could tell me how to add a case? I just forked it and can’t figure that out. Any help you could give is appreciated!

**Comment by PatheticMustan** [comment]
This is really, really late.
If you would like to add a case, you need to make a GIGANTIC item in [script.js](https://github.com/KingofKFCJamal/CaseClicker/blob/master/js/script.js)
Also, near the bottom, you have to configure it so that it actually allows you to see the case, and actually use the case.
